
// Action types Definitions 


export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED'

export const CATEGORY_HEADLINES_AVAILABLE = 'CATEGORY_HEADLINES_AVAILABLE';
export const CATEGORY_HEADLINES_SUCCEEDED = 'CATEGORY_HEADLINES_SUCCEEDED';
export const CATEGORY_HEADLINES_FAILED = 'CATEGORY_HEADLINES_FAILED';